apiVersion: v1
kind: Service
metadata:
  name: vllm-llama31-8b-p150
  labels:
    app: vllm-llama31-8b-p150
spec:
  type: NodePort
  selector:
    app: vllm-llama31-8b-p150
  ports:
    - name: http
      port: 8000
      targetPort: 8000

