## mkdir -p ~/code/vagrant/ubuntu2204 && cd ~/code/vagrant/ubuntu2204
## vagrant box add generic/ubuntu2204 --provider libvirt
## mkdir -p ~/code/vagrant/ubuntu2204 && cd ~/code/vagrant/ubuntu2204
## vagrant box add generic/ubuntu2204 --provider libvirt
## vagrant up

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.hostname = "ubuntu2204"
  config.vm.synced_folder ".", "/home/vagrant/mnt"

  config.vm.provider :libvirt do |vm|
    vm.memory = 4096
    vm.cpus = 2
    vm.storage :file, :size => '20G', :path => 'ubuntu2204SecondDisk.img', :allow_existing => true, :shareable => true, :type => 'raw'
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt install -y build-essential \
        git \
        vim \
        valgrind \
        gcc \
        g++ \
        gdb \
        tree \
        htop \
        docker.io
    apt autoremove -yf
    apt purge -y
    apt clean -y

    groupadd docker
    usermod -aG docker vagrant
    newgrp docker
    docker pull ubuntu:16.04
    ## docker run --rm -it --entrypoint bash ubuntu:16.04&

    ctr images pull docker.io/library/python:3
    ## ctr run --detach -t docker.io/library/python:3 python

    (echo n; echo p; echo 1; echo 2048; echo 41943039; echo w) | sudo fdisk /dev/vdb
    mkfs.ext4 /dev/vdb1
    ## mount /dev/vdb1 /tmp
    ## cp -rf /var/lib/docker/overlay2/d68fc0300107d7955528fe622d7dbe7414fea1822b0cf7ed00bc52c703dbdb4c/diff/. /tmp
    ## cp -rf /var/lib/docker /tmp/var/lib/
    ## cp -rf /var/lib/containerd /tmp/var/lib/
    ## umount /tmp

    dpkg -i /home/vagrant/mnt/assets-osquery-5.12.1.11-Uptycs-LTS.deb
  SHELL
end
