## prepare the system for osquery build.
FROM ubuntu:18.04
RUN apt update && \
    apt install -y sudo make cmake git python python3-pip python3-dev vim valgrind ruby && \
    ln -s /usr/bin/python3 /usr/local/bin/python && \
    pip3 --no-cache-dir install --upgrade pip && \
    rm -rf /var/lib/apt/lists/*

## shortcut commands mk.
RUN echo '#!/bin/bash \n \
    cd ~/code/osquery && \
    make debug -j16 && \
    cd -' > /usr/bin/mk && \
    chmod +x /usr/bin/mk

## shortcut commands mkt.
RUN echo '#!/bin/bash \n \
    cd ~/code/osquery && \
    make debug -j16 && \
    make test_debug -j16 && \
    cd -' > /usr/bin/mkt && \
    chmod +x /usr/bin/mkt

## shortcut commands mkr.
RUN echo '#!/bin/bash \n \
    cd ~/code/osquery && \
    REMEDIATION=1 make debug -j16 && \
    cd -' > /usr/bin/mkr && \
    chmod +x /usr/bin/mkr

## shortcut commands mk-tidy.
RUN echo '#!/bin/bash \n \
    cd ~/code/osquery && \
    make tidy -j16 && \
    cd -' > /usr/bin/mk-tidy && \
    chmod +x /usr/bin/mk-tidy

## shortcut commands mk-valgrind.
RUN echo '#!/bin/bash \n \
    export VALGRIND=1 \n \
    cd ~/code/osquery && \
    make debug -j16 && \
    cd -' > /usr/bin/mk-valgrind && \
    chmod +x /usr/bin/mk-valgrind

RUN gem install dotenv -v 2.8.1

## add a user with sudo privilege.
ARG user
RUN adduser --disabled-password --gecos '' ${user}
RUN adduser ${user} sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
USER ${user}

## creating and fetching osquery repo.
RUN sudo mkdir -p /usr/local/osquery
RUN git config --global --add safe.directory /usr/local/osquery
RUN sudo chown -R ${user}:${user} /usr/local/osquery/

## copying the osquery and changing the ownership to user.
WORKDIR /home/${user}/code/osquery
RUN sudo chown -R ${user}:${user} /home/${user}/code/osquery
COPY --chown=${user}:${user} osquery /home/${user}/code/osquery/

## sysprep and install dependencies and build osquery.
RUN make sysprep && make deps

ENTRYPOINT ["bash", "-l", "-c"]
